language: node_js
node_js:
- node
before_deploy:
- npm run build-storybook
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: storybook-static
  github_token: $GITHUB_TOKEN
  on:
    branch: master
